**Homeworks – Basics in linear algebra and numerical methods, 2021/22. semester I.**

*Week 1*

- name: Nagy, Balázs
- neptun: hpq7oi
- e-mail: [balazs_nagy@outlook.com](balazs_nagy@outlook.com)

In [1]:
import numpy as np

# Ex.a

## Problem

Combine the vectors $u$ and $v$ $\in \mathbb{R}^{10}$ such that you have $(u_1, v_1, u_2, v_2, \dots, u_{10}, v_{10})$. If possible, use vectorized operations.

## Solution

In [2]:
# for easier readability I chose to generate random integers rather then real numbers
n = 10
u = np.random.randint(low=0, high=10, size=n)
v = np.random.randint(low=10, high=20, size=n)
print(
f'''shape u: {u.shape}
shape v: {v.shape}'''
)
print(
f'''u: {u}
v: {v}'''
)

shape u: (10,)
shape v: (10,)
u: [3 4 5 1 7 2 7 7 9 1]
v: [12 11 13 11 16 14 14 15 18 13]


In [3]:
%%timeit
# Solution 1 - using numpy.insert
np.insert(v, np.arange(len(u)), u)

29.8 µs ± 3.09 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
vec1 = np.insert(v, np.arange(len(u)), u)
print(vec1)

[ 3 12  4 11  5 13  1 11  7 16  2 14  7 14  7 15  9 18  1 13]


In [5]:
%%timeit
# Solution 2 - using list comprehension
np.array([[u[i], v[i]] for i in range(len(u))]).flatten()

22 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [6]:
vec2 = np.array([[u[i], v[i]] for i in range(len(u))]).flatten()
print(vec2)

[ 3 12  4 11  5 13  1 11  7 16  2 14  7 14  7 15  9 18  1 13]


In [7]:
%%timeit
# Solution 3 - using vectorised numpy operation
vec3 = np.vstack((u, v)).T.flatten()

8.14 µs ± 559 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
vec3 = np.vstack((u, v)).T.flatten()
print(vec3)

[ 3 12  4 11  5 13  1 11  7 16  2 14  7 14  7 15  9 18  1 13]


The vectorized operation was the fastest.

# Ex.b

## Problem

Take a random vector $v \in \mathbb{R}^{20}$ and remove those elements which are in $[0.4, 0.6]$. You may also use logical `and`.

## Solution

In [9]:
v = np.random.uniform(size=20)
print(
f'''shape v: {v.shape}
v: {v}'''
)

shape v: (20,)
v: [0.44795202 0.32512412 0.25102607 0.0341461  0.52343483 0.56498233
 0.31901142 0.50456662 0.15288751 0.87580105 0.0408424  0.45643589
 0.23381428 0.74942694 0.76248771 0.7415819  0.39808192 0.69553206
 0.05992008 0.62040574]


In [10]:
%%timeit
# Solution 1 - using np.logical_and()
v[~np.logical_and(v>=0.4, v<=0.6)]

3.44 µs ± 181 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
vec1 = v[~np.logical_and(v>=0.4, v<=0.6)]
print(vec1)

[0.32512412 0.25102607 0.0341461  0.31901142 0.15288751 0.87580105
 0.0408424  0.23381428 0.74942694 0.76248771 0.7415819  0.39808192
 0.69553206 0.05992008 0.62040574]


In [12]:
%%timeit
# Solution 2 - using base Python syntax
v[(v>=0.4) & (v<=0.6)]

2.76 µs ± 66.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
vec2 = v[~((v>=0.4) & (v<=0.6))]
print(vec2)

[0.32512412 0.25102607 0.0341461  0.31901142 0.15288751 0.87580105
 0.0408424  0.23381428 0.74942694 0.76248771 0.7415819  0.39808192
 0.69553206 0.05992008 0.62040574]


# Ex.c

## Problem

Take a random vector of length $100$ and compute the vector $v_{\text{new}}$ which is the difference of the neighboring elements with $v_{\text{new}}[j] = v[j]-v[j-1]$ for $j >0$ and $v_{\text{new}}[0]=v[0]$.

## Solution

In [14]:
# for easier readability I chose to generate random integers rather then real numbers
v = np.random.randint(low=0, high=100, size=100)
print(
f'''shape v: {v.shape}
v:
{v}'''
)

shape v: (100,)
v:
[14 46  5 82 95 53 85 41 32 80 56 65 51 29 75 58 62 16 74 57 99 16 74 71
 29 12 64 49 54 61 34 79 87 62 66 46 34 38 76 11  1  9 77 32 31 25 76 73
  5 94 38 77 65 42 40 52  3 34 63 75 21 81 64 24 69 37 83 78 30 64 86 61
 64 24 41 59 12 73 24 96 95 36 84  9 30 67 78 83 93 68 92 25 91 90 63 24
 19 86  8 48]


In [15]:
%%timeit
# Solution 1 - using for loop
v_new1 = []
for i in range(len(v)):
    if i == 0:
        v_new1.append(v[i])
    else:
        v_new1.append(v[i]-v[i-1])
v_new1 = np.array(v_new1)

75.1 µs ± 1.88 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
v_new1 = []
for i in range(len(v)):
    if i == 0:
        v_new1.append(v[i])
    else:
        v_new1.append(v[i]-v[i-1])
v_new1 = np.array(v_new1)
print(v_new1)

[ 14  32 -41  77  13 -42  32 -44  -9  48 -24   9 -14 -22  46 -17   4 -46
  58 -17  42 -83  58  -3 -42 -17  52 -15   5   7 -27  45   8 -25   4 -20
 -12   4  38 -65 -10   8  68 -45  -1  -6  51  -3 -68  89 -56  39 -12 -23
  -2  12 -49  31  29  12 -54  60 -17 -40  45 -32  46  -5 -48  34  22 -25
   3 -40  17  18 -47  61 -49  72  -1 -59  48 -75  21  37  11   5  10 -25
  24 -67  66  -1 -27 -39  -5  67 -78  40]


In [17]:
%%timeit
# Solution 2 - using list comprehension
v_new2 = np.array([v[i]-v[i-1] if i != 0 else v[i] for i in range(len(v))])

70 µs ± 4.86 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [18]:
v_new2 = np.array([v[i]-v[i-1] if i != 0 else v[i] for i in range(len(v))])
print(v_new2)

[ 14  32 -41  77  13 -42  32 -44  -9  48 -24   9 -14 -22  46 -17   4 -46
  58 -17  42 -83  58  -3 -42 -17  52 -15   5   7 -27  45   8 -25   4 -20
 -12   4  38 -65 -10   8  68 -45  -1  -6  51  -3 -68  89 -56  39 -12 -23
  -2  12 -49  31  29  12 -54  60 -17 -40  45 -32  46  -5 -48  34  22 -25
   3 -40  17  18 -47  61 -49  72  -1 -59  48 -75  21  37  11   5  10 -25
  24 -67  66  -1 -27 -39  -5  67 -78  40]


In [19]:
%%timeit
# Solution 3 - using np.diff()
v_new3 = np.diff(v, prepend=v[0])

18.7 µs ± 1.62 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [20]:
v_new3 = np.diff(v, prepend=v[0])
print(f'v: {v.shape}\n{v}')
print(f'vnew: {v_new3.shape}\n{v_new3}')

v: (100,)
[14 46  5 82 95 53 85 41 32 80 56 65 51 29 75 58 62 16 74 57 99 16 74 71
 29 12 64 49 54 61 34 79 87 62 66 46 34 38 76 11  1  9 77 32 31 25 76 73
  5 94 38 77 65 42 40 52  3 34 63 75 21 81 64 24 69 37 83 78 30 64 86 61
 64 24 41 59 12 73 24 96 95 36 84  9 30 67 78 83 93 68 92 25 91 90 63 24
 19 86  8 48]
vnew: (100,)
[  0  32 -41  77  13 -42  32 -44  -9  48 -24   9 -14 -22  46 -17   4 -46
  58 -17  42 -83  58  -3 -42 -17  52 -15   5   7 -27  45   8 -25   4 -20
 -12   4  38 -65 -10   8  68 -45  -1  -6  51  -3 -68  89 -56  39 -12 -23
  -2  12 -49  31  29  12 -54  60 -17 -40  45 -32  46  -5 -48  34  22 -25
   3 -40  17  18 -47  61 -49  72  -1 -59  48 -75  21  37  11   5  10 -25
  24 -67  66  -1 -27 -39  -5  67 -78  40]


The `numpy.diff()` solution is significantly faster than the other solutions.

# Ex.d

## Problem

Take a rectangular grid with $5\times6$ grid points and numbering them $x_1, x_2, \dots, x_{30}$. Construct a matrix $A$ such that
$$
A[i, j] =
\begin{cases}
  -4 & \text{if }x_i=x_j,\\    
  1  & \text{if }x_i, x_j \text{ are vertically or horizontally neighboring,}\\
  0  & \text{anyway.}
\end{cases}
$$
You may use the concept of *Kronecker product*.

## Solution

In [21]:
def create_Aij(dist):
    if dist == 0:
        return -4
    elif (dist == 1) or (dist == 10):
        return 1
    else:
        return 0

In [22]:
def create_Ai(X, label:int, shape:tuple, print_on=False):
    n, m = shape
    D = np.array([label - xij for xij in X])
    Ai = np.array([create_Aij(abs(label-xij)) for xij in X])
    if print_on:
        print('First, create a matrix X where the points are labelled according to their indices:')
        print(X.reshape(n,m))
        print(f"\nSecond, for the given label '{label}' calculate the differences:")
        print(D.reshape(n,m))
        print(f'\nThen apply the definition to acquire the nth row of A, where n={label}:')
        print(Ai)
        print('\n which can also be viewed as:')
        print(Ai.reshape(n,m))
        return None
    return Ai

### Example sol. for one point

In [23]:
shape = (5,6)
label = 33
n, m = shape
X = np.array([int(str(i)+str(j)) for i in range(1,n+1)
                                 for j in range(1,m+1)])
create_Ai(X=X, label=label, shape=shape, print_on=True)

First, create a matrix X where the points are labelled according to their indices:
[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]
 [51 52 53 54 55 56]]

Second, for the given label '33' calculate the differences:
[[ 22  21  20  19  18  17]
 [ 12  11  10   9   8   7]
 [  2   1   0  -1  -2  -3]
 [ -8  -9 -10 -11 -12 -13]
 [-18 -19 -20 -21 -22 -23]]

Then apply the definition to acquire the nth row of A, where n=33:
[ 0  0  0  0  0  0  0  0  1  0  0  0  0  1 -4  1  0  0  0  0  1  0  0  0
  0  0  0  0  0  0]

 which can also be viewed as:
[[ 0  0  0  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  1 -4  1  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  0  0  0  0]]


### Generalized solution

In [24]:
# parameters
shape = (5,6)
n, m = shape

In [25]:
X = np.array([int(str(i)+str(j)) for i in range(1,n+1) for j in range(1,m+1)])
A = np.array([create_Ai(X, x, shape) for x in X])

print('The labels:')
print(X.reshape(n,m))

print('\nThe final result:')
A.reshape(n*m,n*m)

The labels:
[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]
 [51 52 53 54 55 56]]

The final result:


array([[-4,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1, -4,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1, -4,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1, -4,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -4,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1, -4,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0, -4,  1,  0,  0,  0,  0,  1,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  1, -4,  

In [26]:
import pandas as pd
pd.DataFrame(A).to_excel('A_matrix.xlsx')