**Homeworks – Basics in linear algebra and numerical methods, 2021/22. semester I.**

*Week 3*

- name: Nagy, Balázs
- neptun: hpq7oi
- e-mail: [balazs_nagy@outlook.com](balazs_nagy@outlook.com)

In [1]:
import numpy as np

# Ex1

## Problem

![img/week3a.png](img/week3a.png)

## Solution

We can see that for the given $n\times n$ matrix $A$ the following assumption of the iterative approximation is not satisfied:

$A_{j,j}>|A_{j,1}|+|A_{j,j-1}+\dots+|A_{j,n}|$

However, we can rearrange the rows in a way that the condition is satisfied using a simple **permutation matrix**.

In [2]:
A = np.array([[1, 0, 4], [5, 2, -2], [2, 9, 3]])
print(f'Define matrix A, shape: {A.shape}')
print(A)

Define matrix A, shape: (3, 3)
[[ 1  0  4]
 [ 5  2 -2]
 [ 2  9  3]]


In [3]:
def row_sum_excluding_diagonal_element(A):
    n = A.shape[0]
    # helper matrix for scalar products excluding diagonal
    S = np.ones((n,n))
    np.fill_diagonal(S, 0)
    return np.sum(abs(A)*S, axis=1)

In [4]:
print('The diagonal elements of A:')
print(A.diagonal())

print('\n')
print('The rowsums without the diagonal elements:')
print(row_sum_excluding_diagonal_element(A))

print('\n')
print('Check if the A[j,j] > sum A[j, i] i!=j:')
print(A.diagonal() > row_sum_excluding_diagonal_element(A))

The diagonal elements of A:
[1 2 3]


The rowsums without the diagonal elements:
[ 4.  7. 11.]


Check if the A[j,j] > sum A[j, i] i!=j:
[False False False]


In [5]:
print('Matrix A:')
print(A)

P = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]])
print('\n')
print('Define the permutation matrix P:')
print(P)

print('\n')
print('Calculate the matrix product PA:')
print(P@A)

Matrix A:
[[ 1  0  4]
 [ 5  2 -2]
 [ 2  9  3]]


Define the permutation matrix P:
[[0 1 0]
 [0 0 1]
 [1 0 0]]


Calculate the matrix product PA:
[[ 5  2 -2]
 [ 2  9  3]
 [ 1  0  4]]


In [6]:
print('The diagonal elements of A:')
print((P@A).diagonal())

print('\n')
print('The rowsums without the diagonal elements:')
print(row_sum_excluding_diagonal_element(P@A))

print('\n')
print('Check if the A[j,j] > sum A[j, i] i!=j:')
print((P@A).diagonal() > row_sum_excluding_diagonal_element(P@A))

The diagonal elements of A:
[5 9 4]


The rowsums without the diagonal elements:
[4. 5. 1.]


Check if the A[j,j] > sum A[j, i] i!=j:
[ True  True  True]


# Ex2

## Problem

![img/week3b.png](img/week3b.png)

## Solution

I use random integers in hope of an easier visual understanding.

In [7]:
def calc_M(A):
    n = A.shape[0]
    # helper matrix for scalar products excluding diagonal
    S = np.ones((n,n))
    np.fill_diagonal(S, 0)
    return A.diagonal() - np.sum(abs(A)*S, axis=1)

In [8]:
n = 10
A = np.random.randint(low=-5, high=5, size=(n,n))
print(f'Matrix A with shape {A.shape}:')
print(A)

print('\n')
print('The solution vector:')
print(calc_M(A))

Matrix A with shape (10, 10):
[[-2 -2 -2  3 -1  3  4  3 -2  2]
 [-5 -3 -4  2  4  2  3 -2 -5  2]
 [ 3  4 -3 -1 -3 -2  0 -4 -5  0]
 [ 1 -2 -2 -4  3 -5  0 -3  4  1]
 [ 1 -3 -2 -1  1 -2 -3  0  1  0]
 [-3 -5  1  0 -2 -5  4 -4  4 -4]
 [ 2  0  1  4  3  0  3 -1 -3 -2]
 [-1  1 -4  1  4 -3 -3 -2 -5  4]
 [ 4  4  0  1 -5 -3 -5 -2  3 -2]
 [-5 -3 -4 -2  3  4 -2  2  3  2]]


The solution vector:
[-24. -32. -25. -25. -12. -32. -13. -28. -23. -26.]


# Ex3

## Problem

![img/week3c.png](img/week3c.png)

## Solution

In [9]:
from scipy.linalg import lstsq

In [10]:
A = np.random.rand(11,10)
b = np.random.rand(11,)

#results
results = lstsq(A, b)

print(f'Matrix A, shape: {A.shape}')
print(A)

print('\n')
print(f'Vector b, shape: {b.shape}')
print(b)

xh = lstsq(A, b)[0]
print('\n')
print(f'Vector xh, shape: {xh.shape}')
print(xh)

print('\n')
print('Square of the 2-norm for each column')
print(f'using scipy: {results[1]}')
print(f'manually calculating: {sum((A@xh-b)**2)}')

print('\n')
print('The error of the approximation:')
print(np.linalg.norm(A@xh-b))

Matrix A, shape: (11, 10)
[[0.54089695 0.0849392  0.82663515 0.72250916 0.71621568 0.02788751
  0.77592668 0.17855065 0.22396428 0.18541897]
 [0.64428586 0.00154193 0.99865465 0.59258828 0.25499246 0.61787305
  0.93136053 0.01126604 0.87192953 0.70347928]
 [0.79085204 0.61843687 0.49470553 0.84731547 0.27216325 0.00461995
  0.8720457  0.42320351 0.44664511 0.23190653]
 [0.46881425 0.73752553 0.35055942 0.93404853 0.89536618 0.29321404
  0.76423906 0.54408554 0.33481925 0.81452502]
 [0.02349231 0.05654562 0.73173018 0.31273242 0.57866843 0.19420636
  0.72743349 0.87137727 0.10375736 0.5408384 ]
 [0.82478501 0.27280031 0.9125986  0.40806202 0.82082189 0.47374221
  0.42100855 0.73752859 0.28003784 0.72200973]
 [0.39014835 0.36995543 0.74912637 0.3067997  0.46259859 0.59597099
  0.00206932 0.90621465 0.27944336 0.54740872]
 [0.57346024 0.16277826 0.52499513 0.54009552 0.29920455 0.97400302
  0.78165721 0.14775702 0.92005586 0.05053819]
 [0.48295434 0.59044346 0.31411764 0.62333773 0.394900