**Homeworks – Python for Data Science, 2021/22. semester I.**

Excercises 2.
Deadline for submission: 9th of Oct, 2021

- name: Nagy, Balázs
- neptun: hpq7oi
- e-mail: [balazs_nagy@outlook.com](balazs_nagy@outlook.com)

## Queen's Attack

https://www.hackerrank.com/challenges/queens-attack-2/problem



In my solution I imagined the chess board as a 2-dimensional array.

In this chess board array:
- the queen is represented with $-4$,
- the pawns with $-2$,
- the blocked cells by pawns with $-1$,
- the available cells with $1$
- and the indifferent cells with $0$.

This way the sum of the positive values in this matrix is the number of cells the queen can attack.

In [1]:
import numpy as np

In [2]:
def obstacles(arr, queen_pos, pawns_pos):
    arr_mod = arr.copy()
    for pawn_pos in pawns_pos:
        if pawn_pos < queen_pos:
            # if pawn is on the left of the queen
            for i in range(pawn_pos):
                # mark blocked cells with -1
                arr_mod[i] = -1
        if pawn_pos > queen_pos:
            # if pawn is on the right of the queen
            for i in range(pawn_pos+1,len(arr)):
                # mark blocked cells with -1
                arr_mod[i] = -1
    return arr_mod

In [3]:
def queensAttack(n:int, queens_position:tuple, pawns:list) -> int:
    if queens_position in pawns:
        raise ValueError(f'Queen and pawn cannot be in the same position {queens_position}.')
    
    # generate an empty chessboard
    chess_board = np.zeros((n,n), dtype=int)

    # place the queen (-4)
    qr, qc = queens_position # qr: queen's row num, qc: queen's col num
    chess_board[qr, qc] = -4

    # place the pawns (-2)
    for pawn in pawns:
        pr, pc = pawn
        chess_board[pr, pc] = -2
    
    print('Chess board:\n', chess_board,'\n')
    
    # 1. queen's row
    row = chess_board[qr]
    # 2. queen's column
    column = chess_board[:,qc]
    # 3. queen's left diagonal
    left_diag = np.diagonal(chess_board, offset=qc-qr)
    # 4. queen's right diagonal
    right_diag = np.diagonal(np.fliplr(chess_board), offset=(n-qc-1)-qr)

    # store attackable cells in arrays per the orientation of the attack
    queens_attacks = {'row': row, 'column': column, 'left_diag': left_diag, 'right_diag': right_diag}

    num_of_attacks = []
    for orientation, attack in queens_attacks.items():
        # position of the pawn in the array
        pawns_pos = np.where(attack == -2)[0]
        # position of the queen in the array
        queen_pos = np.where(attack == -4)[0][0]
        # modify the 'attack' array -> replace blocked cells from 0 to -1
        attack = obstacles(attack, queen_pos, pawns_pos)
        # mark all cells where the queen can attack with 1
        attack = np.where(attack == 0, 1, attack)
        
        # count and store the attackable cells
        attack_num = np.sum(attack[attack>0])
        num_of_attacks.append(attack_num)
        
        # save the results (although not used)
        queens_attacks[orientation] = attack
        # print the results
        print(f'Attack orientation: {orientation}')
        print('   Pawns positions:', pawns_pos)
        print('   Queens position:', queen_pos)
        print(f'   {orientation}: {attack}')
        print(f'   attack number: {attack_num}')
        print('\n')
    return np.sum(num_of_attacks)

In [4]:
queensAttack(n=5, queens_position=(3, 3), pawns=[(3,2), (2,3), (4,3), (2,2)])

Chess board:
 [[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0 -2 -2  0]
 [ 0  0 -2 -4  0]
 [ 0  0  0 -2  0]] 

Attack orientation: row
   Pawns positions: [2]
   Queens position: 3
   row: [-1 -1 -2 -4  1]
   attack number: 1


Attack orientation: column
   Pawns positions: [2 4]
   Queens position: 3
   column: [-1 -1 -2 -4 -2]
   attack number: 0


Attack orientation: left_diag
   Pawns positions: [2]
   Queens position: 3
   left_diag: [-1 -1 -2 -4  1]
   attack number: 1


Attack orientation: right_diag
   Pawns positions: []
   Queens position: 1
   right_diag: [ 1 -4  1]
   attack number: 2




4

## Validating credit card numbers

https://www.hackerrank.com/challenges/validating-credit-card-number/problem



In [5]:
from collections import Counter

In [6]:
def valid_first_char(cc_num):
    'Check if card number starts with either 4, 5 or 6.'
    return int(cc_num[0]) in ([4, 5, 6])

In [7]:
def valid_length(cc_num, n):
    'Check if the length of card number equals to the given n'
    return len(cc_num) == n

In [8]:
def valid_consecutive(cc_num, n=4):
    'Check if cc_num has n or more consecutive repeated digits. n defaults to 4.'
    return sum([max(Counter(cc_num[i:i+n]).values()) >= n for i in range(len(cc_num))]) == 0

In [9]:
def validate_cc_num(cc_num):
    #########################
    # Case 1 - length is 16
    ########################
    if (valid_length(cc_num, 16) and
            cc_num.isdigit() and
            valid_first_char(cc_num) and
            valid_consecutive(cc_num)):
        return 'Valid'
    #########################
    # Case 2 - length is 19
    ########################
    elif valid_length(cc_num, 19):
        # break into groups
        groups = cc_num.split('-')
        # groups must be size 4
        valid_group_length = sum([not valid_length(group, 4)
                                  for group in groups]) == 0
        # groups must be only digits
        valid_group_digits = sum([not group.isdigit()
                                  for group in groups]) == 0
        if (valid_group_length and
                valid_group_digits and
                valid_first_char(cc_num.replace('-', '')) and
                valid_consecutive(cc_num.replace('-', ''))):
            return 'Valid'
        else:
            return 'Invalid'
    #########################
    # Case 3 - invalid length
    ########################
    else:
        # invalid length
        return 'Invalid'

In [10]:
check_set = {'4253625879615786': 'Valid',
              '4424424424442444': 'Valid',
              '5122-2368-7954-3214': 'Valid',
              '42536258796157867': 'Invalid',
              '4424444424442444': 'Invalid',
              '5122-2368-7954 - 3214': 'Invalid',
              '44244x4424442444': 'Invalid',
              '0525362587961578': 'Invalid',
              '6': 'Invalid',
              '4123456789123456': 'Valid',
              '5123-4567-8912-3456': 'Valid',
              '61234-567-8912-3456': 'Invalid',
              '4123356789123456': 'Valid',
              '5133-3367-8912-3456': 'Invalid',
              '5123 - 3567 - 8912 - 3456': 'Invalid'}

In [11]:
test_result = {example: validate_cc_num(example) == expected_value  for example, expected_value in check_set.items()}
test_result

{'4253625879615786': True,
 '4424424424442444': True,
 '5122-2368-7954-3214': True,
 '42536258796157867': True,
 '4424444424442444': True,
 '5122-2368-7954 - 3214': True,
 '44244x4424442444': True,
 '0525362587961578': True,
 '6': True,
 '4123456789123456': True,
 '5123-4567-8912-3456': True,
 '61234-567-8912-3456': True,
 '4123356789123456': True,
 '5133-3367-8912-3456': True,
 '5123 - 3567 - 8912 - 3456': True}

In [12]:
Counter(test_result.values())

Counter({True: 15})

In [13]:
sum([not passed for passed in test_result.values()]) == 0

True